import type { Metadata } from "next";
import { Pontano_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";

const inter = Pontano_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Navbar />
        {children}
        </body>
    </html>
  );
}
